
POST http://localhost:3002/register
Content-Type: application/json

{
	"user":{
    "email": "admin@gmail.com",
		"username": "admin",
		"password": "admin123",
		"role": "admin"
	}
}

###

POST http://localhost:3002/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin123"
}


###
GET http://localhost:3002/
